### ISSUE TITLE
运行不了

### ISSUE THREAD

**Issue by longbot157** [xiaowenwen1995/AnimeSpider#1]
2020-07-23 14:28:36 [scrapy.core.scraper] ERROR: Error downloading <GET https://www.bilibili.com/bangumi/play/ss33088/>
Traceback (most recent call last):
  File "F:\python\envs\bili\lib\site-packages\twisted\internet\defer.py", line 1386, in _inlineCallbacks
    result = g.send(result)
  File "F:\python\envs\bili\lib\site-packages\scrapy\core\downloader\middleware.py", line 37, in process_request
    response = yield method(request=request, spider=spider)
  File "D:\迅雷下载\AnimeSpider-master\AnimeSpider\middlewares.py", line 142, in process_request
    self.wait.until(EC.text_to_be_present_in_element((By.CSS_SELECTOR, 'a.media-title'), ainmename))
  File "F:\python\envs\bili\lib\site-packages\selenium\webdriver\support\wait.py", line 71, in until
    value = method(self._driver)
  File "F:\python\envs\bili\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 210, in __call__
    return self.text in element_text
TypeError: 'in <string>' requires string as left operand, not int

**Comment by xiaowenwen1995** [comment]
已对该bug进行修复，请更新代码进行验证
